DROP SEQUENCE project_sequence;

CREATE SEQUENCE project_sequence
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE task_sequence;

CREATE SEQUENCE task_sequence
START WITH 1
INCREMENT BY 1;

INSERT INTO COMPANY (CCODE, CNAME, CPHONE, CADDRESS, CPASSWORD)
VALUES ('AA', 'KH정보교육원', '01099998888', '서울시 강남구', '123123');

INSERT INTO DEPT (DEPTNO, CCODE, DEPTNAME)
VALUES ('A', 'AA', 'lclass');

INSERT INTO USERS (USERID, DEPTNO, CCODE, PASSWORD, ENABLED, AUTHORITY, MNAME, MPHONE, MRANK)
VALUES ('kh0001@kh.com', 'A', 'AA', 'khkhkhkh', 0, 'RC', '황대경', '01012341234', 'AAA');

INSERT INTO USERS (USERID, DEPTNO, CCODE, PASSWORD, ENABLED, AUTHORITY, MNAME, MPHONE, MRANK)
VALUES ('kh0002@kh.com', 'A', 'AA', 'khkhkhkh', 0, 'RC', '이지영', '01012341234', 'AAA');

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE, PSTATUS)
VALUES (project_sequence.NEXTVAL, 'kh0001@kh.com', '황스트림', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'), '완료');

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE, PSTATUS)
VALUES (project_sequence.NEXTVAL, 'kh0001@kh.com', '이건2번째야', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'), '진행 중');

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE, PSTATUS)
VALUES (project_sequence.NEXTVAL, 'kh0001@kh.com', '3번째입니다', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'), '진행 중');

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE, PSTATUS)
VALUES (project_sequence.NEXTVAL, 'kh0002@kh.com', '지영님번째입니다', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'), '진행 중');

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE, PSTATUS)
VALUES (project_sequence.NEXTVAL, 'kh0002@kh.com', '지영님입니다', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'), '진행 중');

INSERT INTO TASK (TNO, PNO, USERID, TMEMBER, TTITLE, TCONTENT, TSTATUS, TDATE, TSTARTDATE, TENDDATE)
VALUES (task_sequence.NEXTVAL, 1, 'kh0001@kh.com', 'kh0001@kh.com', '점심 정하기', '정말 고르기 어렵습니다', '완료', SYSDATE, TO_DATE('2023-09-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-10-30 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TASK (TNO, PNO, USERID, TMEMBER, TTITLE, TCONTENT, TSTATUS, TDATE, TSTARTDATE, TENDDATE)
VALUES (task_sequence.NEXTVAL, 2, 'kh0001@kh.com', 'kh0001@kh.com', 'CSS 보완하기', '어렵네 이거...', '진행 중' , SYSDATE, TO_DATE('2023-09-12 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-10-29 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TASK (TNO, PNO, USERID, TMEMBER, TTITLE, TCONTENT, TSTATUS, TDATE, TSTARTDATE, TENDDATE)
VALUES (task_sequence.NEXTVAL, 2, 'kh0001@kh.com', 'kh0001@kh.com', '설계 끝내기', '귀찮네 이거...', '진행 중' , SYSDATE, TO_DATE('2023-09-12 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-10-29 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TASK (TNO, PNO, USERID, TMEMBER, TTITLE, TCONTENT, TSTATUS, TDATE, TSTARTDATE, TENDDATE)
VALUES (task_sequence.NEXTVAL, 2, 'kh0001@kh.com', 'kh0001@kh.com', '하기싫네', '머지 이거...', '진행 중' , SYSDATE, TO_DATE('2023-09-12 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2023-10-29 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));


commit;

SELECT * FROM PROJECT;

desc project;











