-- create sequence
CREATE SEQUENCE project_sequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE task_sequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE schedule_sequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE brestep_sequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE company_sequence
START WITH 4
INCREMENT BY 1;

CREATE SEQUENCE dept_sequence
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE replyrno_sequence
START WITH 1
INCREMENT BY 1;