DROP TABLE  "CHATWRITER";
DROP TABLE "CHATROOM";
DROP TABLE  "CHATMESSAGE";

CREATE TABLE "CHATWRITER" (
	"WRITER"	VARCHAR2(30)	NOT NULL	
);
COMMENT ON COLUMN "CHATWRITER"."WRITER" IS '작성자';

CREATE TABLE "CHATROOM" (
	"ROOMID"	VARCHAR2(50)	NOT NULL,	
	"WRITER"	VARCHAR2(50)	NOT NULL,	
	"ROOMNAME"	VARCHAR2(50)	NOT NULL	
);
COMMENT ON COLUMN "CHATROOM"."ROOMID" IS '채팅방번호';
COMMENT ON COLUMN "CHATROOM"."WRITER" IS '작성자';
COMMENT ON COLUMN "CHATROOM"."ROOMNAME" IS '채팅방이름';


CREATE TABLE "CHATMESSAGE" (
	"WRITER"	VARCHAR2(50)	NOT NULL	,
	"MESSAGE"	VARCHAR2(300)	NOT NULL	,
	"CDATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP NOT NULL,
	"ROOMID"	VARCHAR2(50)	NOT NULL	
);
COMMENT ON COLUMN "CHATMESSAGE"."WRITER" IS '작성자';
COMMENT ON COLUMN "CHATMESSAGE"."MESSAGE" IS '내용';
COMMENT ON COLUMN "CHATMESSAGE"."CDATE" IS '작성 시간';
COMMENT ON COLUMN "CHATMESSAGE"."ROOMID" IS '채팅방번호';



ALTER TABLE "CHATROOM" ADD CONSTRAINT "PK_CHATROOM" PRIMARY KEY (
	"ROOMID"
);


ALTER TABLE "CHATWRITER" ADD CONSTRAINT "PK_CHATWRITER" PRIMARY KEY (
	"WRITER"
);

ALTER TABLE "CHATROOM" ADD CONSTRAINT "FK_CHATWRITER_TO_CHATROOM_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "CHATWRITER" (
	"WRITER"
);

ALTER TABLE "CHATMESSAGE" ADD CONSTRAINT "FK_CHATWRITER_TO_CHATMESSAGE_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "CHATWRITER" (
	"WRITER"
);

ALTER TABLE "CHATMESSAGE" ADD CONSTRAINT "FK_CHATROOM_TO_CHATMESSAGE_1" FOREIGN KEY (
	"ROOMID"
)
REFERENCES "CHATROOM" (
	"ROOMID"
);
commit;
