-- query test용
SELECT MNAME FROM USERS WHERE USERID= 'skin01@gmail.com' AND PASSWORD= '12345';



--CCODE     NOT NULL VARCHAR2(10)  
--CNAME     NOT NULL VARCHAR2(50)  
--CPHONE             VARCHAR2(20)  
--CADDRESS           VARCHAR2(200) 
--CPASSWORD NOT NULL VARCHAR2(20) 

DESC COMPANY;

--INSERT INTO COMPANY VALUES ('C03', '메가박스', NULL, NULL, 'megabox');


--USERID    NOT NULL VARCHAR2(40) 
--DEPTNO    NOT NULL VARCHAR2(10) 
--CCODE     NOT NULL VARCHAR2(10) 
--PASSWORD  NOT NULL VARCHAR2(20) 
--ENABLED   NOT NULL NUMBER(1)    
--AUTHORITY NOT NULL VARCHAR2(3)  
--MNAME              VARCHAR2(30) 
--MPHONE             VARCHAR2(20) 
--MRANK              VARCHAR2(12) 
DESC USERS;

INSERT INTO USERS VALUES ('', 'A', 'C01', DEFAULT, DEFAULT, DEFAULT, '김스킨', '000-0000-0000', '사원');

SELECT MNAME, CNAME, DEPTNAME, USERID, MPHONE, MRANK FROM MEMBER WHERE USERID = 'oliveyoungboss@gmail.com';

SELECT U.MNAME, C.CNAME, D.DEPTNAME, U.MRANK, U.MPHONE
FROM USERS U
INNER JOIN COMPANY C ON U.CCODE=C.CCODE
INNER JOIN DEPT D ON U.DEPTNO=D.DEPTNO AND U.CCODE=D.CCODE
WHERE U.USERID= 'sple@kh.co.kr';
-- 기본적으로 보기 제일 쉬운 코드 값이 많이 뽑혀서 느림

SELECT U.MNAME, U.MRANK, U.MPHONE, C.CNAME, D.DEPTNAME
FROM 
    (SELECT * FROM USERS WHERE USERID='sple@kh.co.kr') U 
    INNER JOIN COMPANY C ON U.CCODE = C.CCODE
    INNER JOIN DEPT D ON U.DEPTNO = D.DEPTNO AND U.CCODE = D.CCODE;
-- USER을 먼저 한명 뽑고 조인시키는 방법
    
SELECT U.USERID, U.MNAME, 
    (SELECT C.CNAME FROM COMPANY C WHERE U.CCODE = C.CCODE) CNAME, D.DEPTNAME
    FROM (SELECT * FROM USERS WHERE USERID = 'sple@kh.co.kr') U
    INNER JOIN DEPT D ON U.DEPTNO = D.DEPTNO AND U.CCODE = D.CCODE;
-- 회사이름을 뽑고 USER도 뽑고 조인시키는 방법, 속도 제일 빠름

SELECT U.USERID, U.MNAME, (SELECT C.CNAME FROM COMPANY C WHERE U.CCODE = C.CCODE) CNAME, D.DEPTNAME 
FROM (SELECT * FROM USERS WHERE USERID = 'sple@kh.co.kr') U INNER JOIN DEPT D ON U.DEPTNO = 
D.DEPTNO AND U.CCODE = D.CCODE; 

INSERT INTO COMPANY (CCODE, CNAME, CPHONE, CADDRESS, CPASSWORD) VALUES ('C' || TO_CHAR(COMPANY_SEQUENCE.NEXTVAL, 
'FM00'), '바나프레소', '1234-5678', '역삼시티점', 12345); 
--SEQUENCE 써서 값넣어보기 TEST

DESC DEPT;
DESC USERS;

INSERT INTO USERS (USERID, DEPTNO, CCODE, PASSWORD, ENABLED, AUTHORITY) VALUES('C005@STREAM.COM', 'D000', 'C005', '12345', 1, 'ROLE_C');

INSERT INTO USERS (USERID, DEPTNO, CCODE, PASSWORD, ENABLED, AUTHORITY)
	 	VALUES ('12345test'||'@stream.com', 'D000', 'C000', default, 1, 'ROLE_C');
        
-- 근태관리

INSERT INTO ATTEND (ATDATE, USERID, ATSTATENO, ATINTIME, ATWORKHOUR) 
VALUES (TO_CHAR(sysdate, 'YYYY-MM-DD'), 'sple@kh.co.kr', 1, TO_CHAR(sysdate, 'YYYY-MM-DD HH24:MI:SS'), 0);

SELECT ATDATE, ATSTATE, ATINTIME, ATOUTTIME, ATWORKHOUR FROM ATTEND JOIN WORKSTATE ON ATTEND.ATSTATENO = WORKSTATE.ATSTATENO WHERE USERID ='sple@kh.co.kr';
