-- query test용
SELECT MNAME FROM USERS WHERE USERID= 'skin01@gmail.com' AND PASSWORD= '12345';



--CCODE     NOT NULL VARCHAR2(10)  
--CNAME     NOT NULL VARCHAR2(50)  
--CPHONE             VARCHAR2(20)  
--CADDRESS           VARCHAR2(200) 
--CPASSWORD NOT NULL VARCHAR2(20) 

DESC COMPANY;

--INSERT INTO COMPANY VALUES ('C03', '메가박스', NULL, NULL, 'megabox');


--USERID    NOT NULL VARCHAR2(40) 
--DEPTNO    NOT NULL VARCHAR2(10) 
--CCODE     NOT NULL VARCHAR2(10) 
--PASSWORD  NOT NULL VARCHAR2(20) 
--ENABLED   NOT NULL NUMBER(1)    
--AUTHORITY NOT NULL VARCHAR2(3)  
--MNAME              VARCHAR2(30) 
--MPHONE             VARCHAR2(20) 
--MRANK              VARCHAR2(12) 
DESC USERS;

INSERT INTO USERS VALUES ('', 'A', 'C01', DEFAULT, DEFAULT, DEFAULT, '김스킨', '000-0000-0000', '사원');

SELECT MNAME, CNAME, DEPTNAME, USERID, MPHONE, MRANK FROM MEMBER WHERE USERID = 'oliveyoungboss@gmail.com';