DROP TABLE "RANK";
DROP TABLE "TASK";
DROP TABLE "MEMBER_PROJECT";
DROP TABLE "CHAT_MEMBER";
DROP TABLE "CHAT";
DROP TABLE "REPLY";
DROP TABLE "COMMUTE";
DROP TABLE "FILES";
DROP TABLE "DEPT";
DROP TABLE "USERS";
DROP TABLE "WORKSTATE";
DROP TABLE "CHATLIST";
DROP TABLE "PROJECT";
DROP TABLE "MEMBER";
DROP TABLE "SCHEDULE";
DROP TABLE "ALARM";


CREATE TABLE "MEMBER" (
	"MNO"	VARCHAR2(10)		NOT NULL,
	"MRANKNO"	NUMBER(1)		NOT NULL,
	"DEPTNO"	VARCHAR2(10)		NOT NULL,
	"MNAME"	VARCHAR2(30)		NOT NULL,
	"MEMAIL"	VARCHAR2(50)		NOT NULL,
	"MPHONE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MNO" IS '사원번호';

COMMENT ON COLUMN "MEMBER"."MRANKNO" IS '직급분류번호';

COMMENT ON COLUMN "MEMBER"."DEPTNO" IS '부서번호';

COMMENT ON COLUMN "MEMBER"."MNAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MPHONE" IS '전화번호';

CREATE TABLE "RANK" (
	"MRANKNO"	NUMBER(1)		NOT NULL,
	"MRANK"	VARCHAR2(12)		NOT NULL
);

COMMENT ON COLUMN "RANK"."MRANKNO" IS '직급분류번호';

COMMENT ON COLUMN "RANK"."MRANK" IS '직급';

CREATE TABLE "PROJECT" (
	"PNO"	VARCHAR2(20)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"PNAME"	VARCHAR2(30)		NOT NULL,
	"PCOMENT"	VARCHAR2(300)		NULL,
	"PACCESS"	VARCHAR2(20)		NOT NULL,
	"PDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PSTARTDATE"	DATE		NULL,
	"PENDDATE"	DATE		NULL
);

COMMENT ON COLUMN "PROJECT"."PNO" IS '프로젝트번호';

COMMENT ON COLUMN "PROJECT"."MNO" IS '관리자';

COMMENT ON COLUMN "PROJECT"."PNAME" IS '프로젝트명';

COMMENT ON COLUMN "PROJECT"."PCOMENT" IS '프로젝트설명';

COMMENT ON COLUMN "PROJECT"."PACCESS" IS '허용/불가';

COMMENT ON COLUMN "PROJECT"."PDATE" IS '작성날짜';

COMMENT ON COLUMN "PROJECT"."PSTARTDATE" IS '프로젝트시작날짜';

COMMENT ON COLUMN "PROJECT"."PENDDATE" IS '프로젝트끝날짜';

CREATE TABLE "CHATLIST" (
	"CHATNO"	VARCHAR2(10)		NOT NULL,
	"PNO"	VARCHAR2(20)		NOT NULL,
	"CHATNAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "CHATLIST"."CHATNO" IS '채팅방번호';

COMMENT ON COLUMN "CHATLIST"."PNO" IS '프로젝트번호';

COMMENT ON COLUMN "CHATLIST"."CHATNAME" IS '채팅방이름';

CREATE TABLE "TASK" (
	"TNO"	VARCHAR2(10)		NOT NULL,
	"PNO"	VARCHAR2(20)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"TMEMBER"	VARCHAR2(10)		NOT NULL,
	"TCONTENT"	VARCHAR2(1200)		NOT NULL,
	"TSTATUS"	VARCHAR2(10)		NOT NULL,
	"TDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TSTARTDATE"	DATE		NULL,
	"TENDDATE"	DATE		NULL
);

COMMENT ON COLUMN "TASK"."TNO" IS '글번호';

COMMENT ON COLUMN "TASK"."PNO" IS '프로젝트번호';

COMMENT ON COLUMN "TASK"."MNO" IS '사원번호';

COMMENT ON COLUMN "TASK"."TMEMBER" IS '담당자';

COMMENT ON COLUMN "TASK"."TCONTENT" IS '글내용';

COMMENT ON COLUMN "TASK"."TSTATUS" IS '진행도';

COMMENT ON COLUMN "TASK"."TDATE" IS '작성날짜';

CREATE TABLE "MEMBER_PROJECT" (
	"PNO"	VARCHAR2(20)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_PROJECT"."PNO" IS '프로젝트번호';

COMMENT ON COLUMN "MEMBER_PROJECT"."MNO" IS '사원번호';

CREATE TABLE "CHAT" (
	"CCNO"	VARCHAR2(10)		NOT NULL,
	"CHATNO"	VARCHAR2(10)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"CCONTENT"	VARCHAR2(300)		NOT NULL,
	"CDATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL
);

COMMENT ON COLUMN "CHAT"."CCNO" IS '대화순번';

COMMENT ON COLUMN "CHAT"."CHATNO" IS '채팅방번호';

COMMENT ON COLUMN "CHAT"."MNO" IS '사원번호';

COMMENT ON COLUMN "CHAT"."CCONTENT" IS '대화내용';

COMMENT ON COLUMN "CHAT"."CDATE" IS '작성날짜';

CREATE TABLE "CHAT_MEMBER" (
	"CHATNO"	VARCHAR2(10)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"CLOSED"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL
);

COMMENT ON COLUMN "CHAT_MEMBER"."CHATNO" IS '채팅방번호';

COMMENT ON COLUMN "CHAT_MEMBER"."MNO" IS '사원번호';

COMMENT ON COLUMN "CHAT_MEMBER"."CLOSED" IS '창닫은시간';

CREATE TABLE "REPLY" (
	"RNO"	VARCHAR2(4)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"WNO"	VARCHAR2(10)		NOT NULL,
	"RCONTENT"	VARCHAR2(300)		NULL,
	"RDATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL
);

COMMENT ON COLUMN "REPLY"."MNO" IS '사원번호';

COMMENT ON COLUMN "REPLY"."WNO" IS '글번호';



CREATE TABLE "COMMUTE" (
	"CDATE"	DATE		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"CSTATENO"	NUMBER(1)		NOT NULL,
	"CSTARTDATE"	DATE		NOT NULL,
	"CENDDATE"	DATE		NULL,
	"CWORKTIME"	NUMBER		NOT NULL,
	"CREASON"	VARCHAR2(300)		NULL
);

COMMENT ON COLUMN "COMMUTE"."CDATE" IS '출퇴근날짜';

COMMENT ON COLUMN "COMMUTE"."MNO" IS '사원번호';

COMMENT ON COLUMN "COMMUTE"."CSTATENO" IS '근무상태번호';

COMMENT ON COLUMN "COMMUTE"."CSTARTDATE" IS '출근시각';

COMMENT ON COLUMN "COMMUTE"."CENDDATE" IS '퇴근시각';

COMMENT ON COLUMN "COMMUTE"."CWORKTIME" IS '근무시간';

COMMENT ON COLUMN "COMMUTE"."CREASON" IS '사유';

CREATE TABLE "FILES" (
	"FNAME"	VARCHAR2(100)		NOT NULL,
	"WNO"	VARCHAR2(10)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"FDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FSIZE"	VARCHAR2(120)		NOT NULL,
	"FPATH"	VARCHAR2(120)		NOT NULL,
	"IMAGESRC"	VARCHAR2(120)		NOT NULL,
	"FORIGINNAME"	VARCHAR2(120)		NOT NULL
);

COMMENT ON COLUMN "FILES"."FNAME" IS '파일명';

COMMENT ON COLUMN "FILES"."WNO" IS '글번호';

COMMENT ON COLUMN "FILES"."MNO" IS '사원번호';

COMMENT ON COLUMN "FILES"."FDATE" IS '업로드일시';

COMMENT ON COLUMN "FILES"."FSIZE" IS '파일크기';

COMMENT ON COLUMN "FILES"."FPATH" IS '파일경로';

COMMENT ON COLUMN "FILES"."IMAGESRC" IS '이미지경로';

COMMENT ON COLUMN "FILES"."FORIGINNAME" IS '파일원본이름';



CREATE TABLE "DEPT" (
	"DEPTNO"	VARCHAR2(10)		NOT NULL,
	"DEPTNAME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "DEPT"."DEPTNO" IS '부서번호';

COMMENT ON COLUMN "DEPT"."DEPTNAME" IS '부서명';



CREATE TABLE "USERS" (
	"USERNAME"	VARCHAR2(20)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"PASSWORD"	VARCHAR2(80)		NOT NULL,
	"ENABLED"	NUMBER(1)	DEFAULT 1	NOT NULL,
	"AUTHORITY"	VARCHAR2(5)	DEFAULT 'C'	NOT NULL
);

COMMENT ON COLUMN "USERS"."MNO" IS '사원번호';

COMMENT ON COLUMN "USERS"."AUTHORITY" IS '권한';



CREATE TABLE "WORKSTATE" (
	"CSTATENO"	NUMBER(1)		NOT NULL,
	"CSTATE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "WORKSTATE"."CSTATENO" IS '근무상태번호';

COMMENT ON COLUMN "WORKSTATE"."CSTATE" IS '근무상태';



CREATE TABLE "SCHEDULE" (
	"SNO"	VARCHAR2(10)		NOT NULL,
	"MNO"	VARCHAR2(10)		NULL,
	"SSTARTDATE"	VARCHAR2(20)		NOT NULL,
	"SENDDATE"	VARCHAR2(20)		NOT NULL,
	"SPLACE"	VARCHAR2(50)		NULL,
	"SMEMO"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "SCHEDULE"."SNO" IS '일정번호';

COMMENT ON COLUMN "SCHEDULE"."MNO" IS '참석자';



CREATE TABLE "ALARM" (
	"RNO"	VARCHAR2(4)		NOT NULL,
	"MNO"	VARCHAR2(10)		NOT NULL,
	"PNO"	VARCHAR2(20)		NOT NULL,
	"TNO"	VARCHAR2(10)		NOT NULL,
	"MNO2"	VARCHAR2(10)		NOT NULL,
	"ACOUNT"	NUMBER(1)		NOT NULL,
	"ADATE"	DATE		NOT NULL,
	"ACONTENT"	VARCHAR2(60)		NOT NULL
);

COMMENT ON COLUMN "ALARM"."RNO" IS '댓글번호';

COMMENT ON COLUMN "ALARM"."MNO" IS '사원번호';

COMMENT ON COLUMN "ALARM"."PNO" IS '프로젝트번호';

COMMENT ON COLUMN "ALARM"."TNO" IS '글번호';

COMMENT ON COLUMN "ALARM"."MNO2" IS '사원번호';

COMMENT ON COLUMN "ALARM"."ACOUNT" IS '미확인개수';

COMMENT ON COLUMN "ALARM"."ADATE" IS '알림 생성일';

COMMENT ON COLUMN "ALARM"."ACONTENT" IS '알림내용';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MNO"
);

ALTER TABLE "RANK" ADD CONSTRAINT "PK_RANK" PRIMARY KEY (
	"MRANKNO"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY (
	"PNO"
);

ALTER TABLE "CHATLIST" ADD CONSTRAINT "PK_CHATLIST" PRIMARY KEY (
	"CHATNO"
);

ALTER TABLE "TASK" ADD CONSTRAINT "PK_TASK" PRIMARY KEY (
	"TNO"
);

ALTER TABLE "MEMBER_PROJECT" ADD CONSTRAINT "PK_MEMBER_PROJECT" PRIMARY KEY (
	"PNO",
	"MNO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CCNO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "PK_CHAT_MEMBER" PRIMARY KEY (
	"CHATNO",
	"MNO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"RNO"
);

ALTER TABLE "COMMUTE" ADD CONSTRAINT "PK_COMMUTE" PRIMARY KEY (
	"CDATE",
	"MNO"
);

ALTER TABLE "FILES" ADD CONSTRAINT "PK_FILES" PRIMARY KEY (
	"FNAME"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY (
	"DEPTNO"
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (
	"USERNAME"
);

ALTER TABLE "WORKSTATE" ADD CONSTRAINT "PK_WORKSTATE" PRIMARY KEY (
	"CSTATENO"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY (
	"SNO"
);

ALTER TABLE "MEMBER_PROJECT" ADD CONSTRAINT "FK_PROJECT_TO_MEMBER_PROJECT_1" FOREIGN KEY (
	"PNO"
)
REFERENCES "PROJECT" (
	"PNO"
);

ALTER TABLE "MEMBER_PROJECT" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_PROJECT_1" FOREIGN KEY (
	"MNO"
)
REFERENCES "MEMBER" (
	"MNO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "FK_CHATLIST_TO_CHAT_MEMBER_1" FOREIGN KEY (
	"CHATNO"
)
REFERENCES "CHATLIST" (
	"CHATNO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_MEMBER_1" FOREIGN KEY (
	"MNO"
)
REFERENCES "MEMBER" (
	"MNO"
);

ALTER TABLE "COMMUTE" ADD CONSTRAINT "FK_MEMBER_TO_COMMUTE_1" FOREIGN KEY (
	"MNO"
)
REFERENCES "MEMBER" (
	"MNO"
);

