--COMMENT ON COLUMN "CHAT"."CCNO" IS '대화순번';
--COMMENT ON COLUMN "CHAT"."CHATNO" IS '채팅방번호';
--COMMENT ON COLUMN "CHAT"."USERID" IS 'EMAIL';
--COMMENT ON COLUMN "CHAT"."CCONTENT" IS '대화내용';
--COMMENT ON COLUMN "CHAT"."CDATE" IS '작성날짜';
--COMMENT ON COLUMN "CHATLIST"."CHATNO" IS '채팅방번호';
--COMMENT ON COLUMN "CHATLIST"."CHATNAME" IS '채팅방이름'
--COMMENT ON COLUMN "CHAT_MEMBER"."CHATNO" IS '채팅방번호';
--COMMENT ON COLUMN "CHAT_MEMBER"."USERID" IS 'EMAIL';
SELECT
    *
FROM users;

SELECT *
FROM chat;

SELECT  *
FROM CHATLIST;

SELECT  *
FROM CHAT_member;

TRUNCATE table chat_member;


INSERT INTO chat_member( CHATNO,USERID) VALUES (11,'kh0001@kh.com');
INSERT INTO chat_member( CHATNO,USERID) VALUES (22,'kh0002@kh.com');

INSERT INTO chatLIST( CHATNO,CHATNAME) VALUES (chat_sequence.NEXTVAL,'채팅방이름1');
INSERT INTO chatLIST( CHATNO,CHATNAME) VALUES (chat_sequence.NEXTVAL,'채팅방이름2');
INSERT INTO chatLIST( CHATNO,CHATNAME) VALUES (chat_sequence.NEXTVAL,'채팅방이름8');
