INSERT INTO MEMBER_SCHEDULE (SNO, ATTENUSERID)
VALUES ('1','sple@kh.co.kr');
INSERT INTO MEMBER_SCHEDULE (SNO, ATTENUSERID)
VALUES ('1','sample@kh.co.kr');
INSERT INTO MEMBER_SCHEDULE (SNO, ATTENUSERID)
VALUES ('1','mplsam@kh.co.kr');
INSERT INTO MEMBER_SCHEDULE (SNO, ATTENUSERID)
VALUES ('1','fffll@ctest.co.kr');
        
