DROP SEQUENCE project_sequence;

CREATE SEQUENCE project_sequence
START WITH 1
INCREMENT BY 1;

INSERT INTO COMPANY (CCODE, CNAME, CPHONE, CADDRESS, CPASSWORD)
VALUES ('AA', 'KH정보교육원', '01099998888', '서울시 강남구', '123123');

INSERT INTO DEPT (DEPTNO, CCODE, DEPTNAME)
VALUES ('A', 'AA', 'lclass');

INSERT INTO USERS (USERID, DEPTNO, CCODE, PASSWORD, ENABLED, AUTHORITY, MNAME, MPHONE, MRANK)
VALUES ('kh0001@kh.com', 'A', 'AA', 'khkhkhkh', 0, 'RC', '황대경', '01012341234', 'AAA');

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE)
VALUES (project_sequence.NEXTVAL, 'kh0001@kh.com', '황스트림', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'));

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE)
VALUES (project_sequence.NEXTVAL, 'kh0001@kh.com', '이건2번째야', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'));

INSERT INTO PROJECT (PNO, USERID, PNAME, PCOMENT, PACCESS, PDATE, PSTARTDATE, PENDDATE)
VALUES (project_sequence.NEXTVAL, 'kh0001@kh.com', '3번째입니다', '프로젝트 해야합니다.', 'ACCESS', TO_DATE('2023-09-06', 'YYYY-MM-DD'), TO_DATE('2023-09-10', 'YYYY-MM-DD'), TO_DATE('2023-10-30', 'YYYY-MM-DD'));

commit;













